### ISSUE TITLE
lofar 3.2.5-3.2.9 doesn't support casacore 3.0/KERN-5

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#181]
```
[  0%] Building CXX object LCS/Common/src/CMakeFiles/common.dir/Allocator.cc.o
cd /build/lofar-3.2.5/build/gnucxx11_opt/LCS/Common/src && /usr/bin/g++  -DHAVE_PTHREAD_H -DLOFARLOGGER_PACKAGE=\"LCS.Common\" -DUSE_THREADS -Dcommon_EXPORTS -I/build/lofar-3.2.5/build/gnucxx11_opt/include -isystem /usr/inclu
de/casacore -isystem /usr/include/hdf5/serial -I/build/lofar-3.2.5/build/gnucxx11_opt/include/Package__Version  -std=gnu++11 -W -Wall -Woverloaded-virtual -Wno-unknown-pragmas -fopenmp -pthread -g -O2 -fPIC   -o CMakeFiles/co
mmon.dir/Allocator.cc.o -c /build/lofar-3.2.5/LCS/Common/src/Allocator.cc
In file included from /build/lofar-3.2.5/build/gnucxx11_opt/include/Common/LofarLog4Cplus.h:30:0,
                 from /build/lofar-3.2.5/build/gnucxx11_opt/include/Common/LofarLogger.h:34,
                 from /build/lofar-3.2.5/LCS/Common/src/Allocator.cc:28:
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:49:30: error: 'casa' has not been declared
   class CasaLogSink : public casa::LogSinkInterface
                              ^~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:49:36: error: expected '{' before 'LogSinkInterface'
   class CasaLogSink : public casa::LogSinkInterface
                                    ^~~~~~~~~~~~~~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:51:3: error: expected primary-expression before 'public'
   public:
   ^~~~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:51:3: error: expected '}' before 'public'
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:57:27: error: 'casa' has not been declared
     explicit CasaLogSink (casa::LogMessage::Priority filter);
                           ^~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:57:54: error: expected ')' before 'filter'
     explicit CasaLogSink (casa::LogMessage::Priority filter);
                                                      ^~~~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:58:27: error: expected unqualified-id before 'const'
     explicit CasaLogSink (const casa::LogFilterInterface& filter);
                           ^~~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:58:27: error: expected ')' before 'const'
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:61:19: error: expected constructor, destructor, or type conversion before ';' token
     ~CasaLogSink();
                   ^
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:67:13: error: 'casa' does not name a type; did you mean 'cosl'?
     virtual casa::Bool postLocally (const casa::LogMessage& message);
             ^~~~
             cosl
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:70:5: error: 'virtual' outside class declaration
     virtual void clearLocally();
     ^~~~~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:73:12: error: 'casa' does not name a type; did you mean 'cosl'?
     static casa::String localId();
            ^~~~
            cosl
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:75:5: error: 'casa' does not name a type; did you mean 'cosl'?
     casa::String id() const;
     ^~~~
     cosl
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:77:3: error: expected unqualified-id before 'private'
   private:
   ^~~~~~~
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:81:53: error: 'LOFAR::CasaLogSink& LOFAR::operator=(const LOFAR::CasaLogSink&)' must be a nonstatic member function
     CasaLogSink& operator= (const CasaLogSink& other);
                                                     ^
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:85:1: error: expected declaration before '}' token
 } // end namespace
 ^
/build/lofar-3.2.5/build/gnucxx11_opt/include/Common/CasaLogSink.h:64:17: warning: 'void LOFAR::attach()' declared 'static' but never defined [-Wunused-function]
     static void attach();
                 ^~~~~~
LCS/Common/src/CMakeFiles/common.dir/build.make:89: recipe for target 'LCS/Common/src/CMakeFiles/common.dir/Allocator.cc.o' failed
```

**Comment by gijzelaerr** [comment]
wsclean depends on LOFAR (for the beam model)

**Comment by gijzelaerr** [comment]
dp3 depends on lofar also

**Comment by gijzelaerr** [comment]
lofar 3.2.7 doesn't compile with casacore 3.0 also

**Comment by gijzelaerr** [comment]
still a nope with 3.2.9

**Comment by gijzelaerr** [comment]
tammo-jan wrote: "The RO is now converting LOFAR to casacore 3.0, it's finished on a branch already (cobalt 2.0 branch). However the tests seem to be failing, and apparently reproducing the supposed bug takes days."

As soon as the porting is finished and the code is compiling I will upload it to KERN-5.

**Comment by gijzelaerr** [comment]
lofar 4.0.17 has been uplaoded to KERN-6 and KERN-dev
